spring:
  application:
    name: configuration
  cloud:
    config:
      enabled: false

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
  client:
    registerWithEureka: false
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URI:http://localhost:8761}/eureka/